kind: pipeline
type: kubernetes
name: default
steps:
  - name: publish-private
    image: plugins/docker
    settings:
      repo: registry.paradas.co/do-dns-updater
      registry: registry.paradas.co
      username:
        from_secret: docker_username
      password: 
        from_secret: docker_password
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER}
  - name: publish-docker-io
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password: 
        from_secret: DOCKERHUB_PASSWORD
      repo: jparadasb/do-dns-updater
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER}
      when:
        ref:
          - refs/tags/v*
