name: Docker Image CI DEV

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v2
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to private registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: do-dns-updater # you'll use this in the next step
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          jparadasb/do-dns-updater
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=sha
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.do-dns-updater.outputs.tags }}
        labels: ${{ steps.do-dns-updater.outputs.labels }}
